-- 0001_init.up.sql — baseline schema snapshot for Node-Pulse Pulse API.
--
-- Generated by pg_dump from the canonical schema produced by the previous
-- inline Go migrations (internal/db/migrations.go, 27 steps). This baseline
-- replaces those inline migrations as the single source of truth going
-- forward; subsequent schema changes each get their own numbered file.
--
-- DO NOT EDIT by hand. To change the schema, add 0002_*.up.sql / .down.sql.
CREATE FUNCTION public.update_probes_updated_at_func() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
		BEGIN
			NEW.updated_at = NOW();
			RETURN NEW;
		END;
		$$;
CREATE TABLE public.alert_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    metric character varying NOT NULL,
    threshold numeric NOT NULL,
    current_value numeric NOT NULL,
    level character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.alert_notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    alert_id uuid NOT NULL,
    user_id uuid,
    user_name character varying(255) DEFAULT 'System'::character varying NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT chk_alert_note_content_not_empty CHECK ((length(TRIM(BOTH FROM content)) > 0))
);
CREATE TABLE public.alert_records (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    alert_event_id uuid NOT NULL,
    node_id uuid NOT NULL,
    metric character varying NOT NULL,
    level character varying NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT chk_alert_record_status CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'resolved'::character varying])::text[])))
);
CREATE TABLE public.alert_status_history (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    alert_id uuid NOT NULL,
    from_status character varying,
    to_status character varying NOT NULL,
    user_id uuid,
    user_name character varying(255) DEFAULT 'System'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT chk_alert_status_history_from_status CHECK (((from_status IS NULL) OR ((from_status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'resolved'::character varying])::text[])))),
    CONSTRAINT chk_alert_status_history_to_status CHECK (((to_status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'resolved'::character varying])::text[])))
);
CREATE TABLE public.alert_suppressions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    metric character varying NOT NULL,
    suppressed_until timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.alerts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    metric character varying NOT NULL,
    threshold numeric(10,2) NOT NULL,
    level character varying NOT NULL,
    node_id uuid,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT alerts_level_check CHECK (((level)::text = ANY ((ARRAY['P0'::character varying, 'P1'::character varying, 'P2'::character varying])::text[]))),
    CONSTRAINT alerts_metric_check CHECK (((metric)::text = ANY ((ARRAY['latency'::character varying, 'packet_loss_rate'::character varying, 'jitter'::character varying])::text[]))),
    CONSTRAINT alerts_threshold_check CHECK ((threshold > (0)::numeric))
);
CREATE TABLE public.api_keys (
    id integer NOT NULL,
    key_id character varying(20) NOT NULL,
    key_hash text NOT NULL,
    key_prefix character varying(20) NOT NULL,
    user_id uuid,
    service_account_id uuid,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    last_used_at timestamp with time zone,
    CONSTRAINT chk_owner_xor CHECK (((((user_id IS NOT NULL))::integer + ((service_account_id IS NOT NULL))::integer) = 1))
);
CREATE SEQUENCE public.api_keys_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.api_keys_id_seq OWNED BY public.api_keys.id;
CREATE TABLE public.auth_audit_logs (
    id bigint NOT NULL,
    event_type character varying(100) NOT NULL,
    user_id uuid,
    service_account_id uuid,
    session_id uuid,
    ip_address inet,
    user_agent text,
    details jsonb,
    created_at timestamp with time zone DEFAULT now()
);
CREATE SEQUENCE public.auth_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.auth_audit_logs_id_seq OWNED BY public.auth_audit_logs.id;
CREATE TABLE public.beacon_config_history (
    id bigint NOT NULL,
    beacon_id uuid NOT NULL,
    version integer NOT NULL,
    config jsonb NOT NULL,
    changed_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_by character varying(255) DEFAULT 'system'::character varying NOT NULL
);
CREATE SEQUENCE public.beacon_config_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.beacon_config_history_id_seq OWNED BY public.beacon_config_history.id;
CREATE TABLE public.beacon_configs (
    beacon_id uuid NOT NULL,
    probes jsonb DEFAULT '[]'::jsonb NOT NULL,
    interval_seconds integer DEFAULT 60 NOT NULL,
    timeout_seconds integer DEFAULT 5 NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    last_ack_version integer,
    last_ack_at timestamp with time zone,
    last_ack_status character varying(20),
    last_ack_error text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT beacon_configs_interval_seconds_check CHECK ((interval_seconds >= 5)),
    CONSTRAINT beacon_configs_timeout_seconds_check CHECK ((timeout_seconds >= 1)),
    CONSTRAINT beacon_configs_version_check CHECK ((version >= 1))
);
CREATE TABLE public.metrics (
    id bigint NOT NULL,
    node_id uuid NOT NULL,
    probe_id uuid NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    latency_ms numeric(10,2),
    packet_loss_rate numeric(5,4),
    jitter_ms numeric(10,2),
    is_aggregated boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);
CREATE SEQUENCE public.metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.metrics_id_seq OWNED BY public.metrics.id;
CREATE TABLE public.mtr_results (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    probe_id character varying(255),
    target character varying(255) NOT NULL,
    success boolean NOT NULL,
    total_hops integer DEFAULT 0 NOT NULL,
    hops jsonb DEFAULT '[]'::jsonb NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT mtr_results_total_hops_check CHECK ((total_hops >= 0))
);
CREATE TABLE public.nodes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    ip character varying(45) NOT NULL,
    region character varying(100) NOT NULL,
    tags jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    last_heartbeat timestamp with time zone,
    last_report_time timestamp with time zone,
    status character varying(20) DEFAULT 'connecting'::character varying,
    CONSTRAINT chk_node_status CHECK (((status)::text = ANY ((ARRAY['online'::character varying, 'offline'::character varying, 'connecting'::character varying])::text[])))
);
CREATE TABLE public.password_reset_tokens (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone DEFAULT now()
);
CREATE SEQUENCE public.password_reset_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;
CREATE TABLE public.permissions (
    id integer NOT NULL,
    resource character varying(50) NOT NULL,
    action character varying(20) NOT NULL,
    description text
);
CREATE SEQUENCE public.permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.permissions_id_seq OWNED BY public.permissions.id;
CREATE TABLE public.probes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    type character varying(10) NOT NULL,
    target character varying(255) NOT NULL,
    port integer NOT NULL,
    interval_seconds integer NOT NULL,
    count integer NOT NULL,
    timeout_seconds integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT probes_count_check CHECK (((count >= 1) AND (count <= 100))),
    CONSTRAINT probes_interval_seconds_check CHECK (((interval_seconds >= 60) AND (interval_seconds <= 300))),
    CONSTRAINT probes_port_check CHECK (((port >= 1) AND (port <= 65535))),
    CONSTRAINT probes_timeout_seconds_check CHECK (((timeout_seconds >= 1) AND (timeout_seconds <= 30))),
    CONSTRAINT probes_type_check CHECK (((type)::text = ANY ((ARRAY['TCP'::character varying, 'UDP'::character varying])::text[])))
);
CREATE TABLE public.rate_limits (
    id bigint NOT NULL,
    key text NOT NULL,
    window_type character varying(10) NOT NULL,
    window_start timestamp with time zone NOT NULL,
    request_count integer DEFAULT 1
);
CREATE SEQUENCE public.rate_limits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.rate_limits_id_seq OWNED BY public.rate_limits.id;
CREATE TABLE public.refresh_tokens (
    id integer NOT NULL,
    token_id uuid DEFAULT gen_random_uuid() NOT NULL,
    token_hash text NOT NULL,
    user_id uuid NOT NULL,
    session_id uuid,
    expires_at timestamp with time zone NOT NULL,
    max_valid_until timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by uuid,
    user_agent text,
    ip_address inet,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE SEQUENCE public.refresh_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;
CREATE TABLE public.role_permissions (
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    granted_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text,
    is_system_role boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);
CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;
CREATE TABLE public.service_accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone
);
CREATE TABLE public.sessions (
    session_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    device_id character varying(255),
    ip_address inet,
    user_agent text,
    remember_me boolean DEFAULT false,
    expires_at timestamp with time zone NOT NULL,
    max_valid_until timestamp with time zone NOT NULL,
    last_activity_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.token_blacklist (
    jti text NOT NULL,
    user_id uuid,
    revoked_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    reason text
);
CREATE TABLE public.users (
    user_id uuid NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(255),
    password_hash character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    failed_login_attempts integer DEFAULT 0,
    locked_until timestamp with time zone,
    mfa_enabled boolean DEFAULT false,
    mfa_secret text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.webhook_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    webhook_id uuid NOT NULL,
    alert_event_id uuid NOT NULL,
    status character varying NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    error_message text,
    sent_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.webhooks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    url character varying NOT NULL,
    event_format jsonb,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE ONLY public.api_keys ALTER COLUMN id SET DEFAULT nextval('public.api_keys_id_seq'::regclass);
ALTER TABLE ONLY public.auth_audit_logs ALTER COLUMN id SET DEFAULT nextval('public.auth_audit_logs_id_seq'::regclass);
ALTER TABLE ONLY public.beacon_config_history ALTER COLUMN id SET DEFAULT nextval('public.beacon_config_history_id_seq'::regclass);
ALTER TABLE ONLY public.metrics ALTER COLUMN id SET DEFAULT nextval('public.metrics_id_seq'::regclass);
ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);
ALTER TABLE ONLY public.permissions ALTER COLUMN id SET DEFAULT nextval('public.permissions_id_seq'::regclass);
ALTER TABLE ONLY public.rate_limits ALTER COLUMN id SET DEFAULT nextval('public.rate_limits_id_seq'::regclass);
ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);
ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);
ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.alert_notes
    ADD CONSTRAINT alert_notes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.alert_records
    ADD CONSTRAINT alert_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.alert_status_history
    ADD CONSTRAINT alert_status_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.alert_suppressions
    ADD CONSTRAINT alert_suppressions_node_id_metric_key UNIQUE (node_id, metric);
ALTER TABLE ONLY public.alert_suppressions
    ADD CONSTRAINT alert_suppressions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash);
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_id_key UNIQUE (key_id);
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.auth_audit_logs
    ADD CONSTRAINT auth_audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.beacon_config_history
    ADD CONSTRAINT beacon_config_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.beacon_configs
    ADD CONSTRAINT beacon_configs_pkey PRIMARY KEY (beacon_id);
ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mtr_results
    ADD CONSTRAINT mtr_results_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_resource_action_key UNIQUE (resource, action);
ALTER TABLE ONLY public.probes
    ADD CONSTRAINT probes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rate_limits
    ADD CONSTRAINT rate_limits_key_window_type_window_start_key UNIQUE (key, window_type, window_start);
ALTER TABLE ONLY public.rate_limits
    ADD CONSTRAINT rate_limits_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_id_key UNIQUE (token_id);
ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.service_accounts
    ADD CONSTRAINT service_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);
ALTER TABLE ONLY public.token_blacklist
    ADD CONSTRAINT token_blacklist_pkey PRIMARY KEY (jti);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);
ALTER TABLE ONLY public.webhook_logs
    ADD CONSTRAINT webhook_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.webhooks
    ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);
CREATE INDEX idx_alert_events_created_at ON public.alert_events USING btree (created_at DESC);
CREATE INDEX idx_alert_events_metric ON public.alert_events USING btree (metric);
CREATE INDEX idx_alert_events_node_created ON public.alert_events USING btree (node_id, created_at DESC);
CREATE INDEX idx_alert_events_node_id ON public.alert_events USING btree (node_id);
CREATE INDEX idx_alert_notes_alert_id ON public.alert_notes USING btree (alert_id, created_at);
CREATE INDEX idx_alert_notes_created_at ON public.alert_notes USING btree (created_at DESC);
CREATE INDEX idx_alert_notes_user_id ON public.alert_notes USING btree (user_id);
CREATE INDEX idx_alert_records_created_at ON public.alert_records USING btree (created_at DESC);
CREATE INDEX idx_alert_records_level ON public.alert_records USING btree (level);
CREATE INDEX idx_alert_records_node_created ON public.alert_records USING btree (node_id, created_at DESC);
CREATE INDEX idx_alert_records_node_id ON public.alert_records USING btree (node_id);
CREATE INDEX idx_alert_records_status ON public.alert_records USING btree (status);
CREATE INDEX idx_alert_records_status_created ON public.alert_records USING btree (status, created_at DESC);
CREATE INDEX idx_alert_status_history_alert_id ON public.alert_status_history USING btree (alert_id, created_at);
CREATE INDEX idx_alert_status_history_created_at ON public.alert_status_history USING btree (created_at DESC);
CREATE INDEX idx_alert_status_history_user_id ON public.alert_status_history USING btree (user_id);
CREATE INDEX idx_alert_suppressions_node_metric ON public.alert_suppressions USING btree (node_id, metric);
CREATE INDEX idx_alert_suppressions_until ON public.alert_suppressions USING btree (suppressed_until);
CREATE INDEX idx_alerts_enabled ON public.alerts USING btree (enabled);
CREATE INDEX idx_alerts_metric ON public.alerts USING btree (metric);
CREATE INDEX idx_alerts_node_id ON public.alerts USING btree (node_id);
CREATE INDEX idx_api_keys_active_expires ON public.api_keys USING btree (is_active, expires_at);
CREATE INDEX idx_api_keys_key_hash ON public.api_keys USING btree (key_hash);
CREATE INDEX idx_api_keys_prefix ON public.api_keys USING btree (key_prefix);
CREATE INDEX idx_api_keys_service_account_id ON public.api_keys USING btree (service_account_id);
CREATE INDEX idx_api_keys_user_id ON public.api_keys USING btree (user_id);
CREATE INDEX idx_audit_events ON public.auth_audit_logs USING btree (event_type, created_at DESC);
CREATE INDEX idx_audit_ips ON public.auth_audit_logs USING btree (ip_address, created_at DESC);
CREATE INDEX idx_audit_service_accounts ON public.auth_audit_logs USING btree (service_account_id, created_at DESC);
CREATE INDEX idx_audit_users ON public.auth_audit_logs USING btree (user_id, created_at DESC);
CREATE INDEX idx_beacon_config_history_beacon_changed ON public.beacon_config_history USING btree (beacon_id, changed_at DESC);
CREATE INDEX idx_metrics_aggregated ON public.metrics USING btree (is_aggregated, "timestamp" DESC);
CREATE INDEX idx_metrics_node_timestamp ON public.metrics USING btree (node_id, "timestamp" DESC);
CREATE INDEX idx_metrics_probe_timestamp ON public.metrics USING btree (probe_id, "timestamp" DESC);
CREATE INDEX idx_metrics_timestamp ON public.metrics USING btree ("timestamp" DESC);
CREATE INDEX idx_mtr_results_node_completed ON public.mtr_results USING btree (node_id, completed_at DESC);
CREATE INDEX idx_mtr_results_target ON public.mtr_results USING btree (target);
CREATE INDEX idx_nodes_created_at ON public.nodes USING btree (created_at DESC);
CREATE INDEX idx_nodes_ip ON public.nodes USING btree (ip);
CREATE INDEX idx_nodes_last_heartbeat ON public.nodes USING btree (last_heartbeat);
CREATE INDEX idx_nodes_region ON public.nodes USING btree (region);
CREATE INDEX idx_password_reset_tokens_expires_at ON public.password_reset_tokens USING btree (expires_at);
CREATE INDEX idx_password_reset_tokens_hash ON public.password_reset_tokens USING btree (token_hash);
CREATE INDEX idx_password_reset_tokens_user_id ON public.password_reset_tokens USING btree (user_id);
CREATE INDEX idx_probes_node_id ON public.probes USING btree (node_id);
CREATE INDEX idx_probes_type ON public.probes USING btree (type);
CREATE INDEX idx_rate_limits_lookup ON public.rate_limits USING btree (key, window_type, window_start);
CREATE INDEX idx_refresh_tokens_session ON public.refresh_tokens USING btree (session_id) WHERE (session_id IS NOT NULL);
CREATE INDEX idx_refresh_tokens_token_hash ON public.refresh_tokens USING btree (token_hash);
CREATE INDEX idx_refresh_tokens_token_id ON public.refresh_tokens USING btree (token_id);
CREATE INDEX idx_refresh_tokens_user_revoked ON public.refresh_tokens USING btree (user_id, revoked_at);
CREATE INDEX idx_sessions_device ON public.sessions USING btree (device_id) WHERE (device_id IS NOT NULL);
CREATE INDEX idx_sessions_expires_at ON public.sessions USING btree (expires_at);
CREATE INDEX idx_sessions_user_expired ON public.sessions USING btree (user_id, expires_at DESC);
CREATE INDEX idx_sessions_user_id ON public.sessions USING btree (user_id);
CREATE INDEX idx_token_blacklist_expires ON public.token_blacklist USING btree (expires_at);
CREATE INDEX idx_token_blacklist_user ON public.token_blacklist USING btree (user_id, expires_at);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_locked ON public.users USING btree (locked_until) WHERE (locked_until IS NOT NULL);
CREATE INDEX idx_users_username ON public.users USING btree (username);
CREATE INDEX idx_webhook_logs_alert_event_id ON public.webhook_logs USING btree (alert_event_id);
CREATE INDEX idx_webhook_logs_created_at ON public.webhook_logs USING btree (created_at DESC);
CREATE INDEX idx_webhook_logs_status ON public.webhook_logs USING btree (status);
CREATE INDEX idx_webhook_logs_webhook_id ON public.webhook_logs USING btree (webhook_id);
CREATE INDEX idx_webhooks_enabled ON public.webhooks USING btree (enabled);
CREATE INDEX idx_webhooks_url ON public.webhooks USING btree (url);
CREATE TRIGGER update_probes_updated_at BEFORE UPDATE ON public.probes FOR EACH ROW EXECUTE FUNCTION public.update_probes_updated_at_func();
ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alert_notes
    ADD CONSTRAINT alert_notes_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alert_records(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alert_notes
    ADD CONSTRAINT alert_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;
ALTER TABLE ONLY public.alert_records
    ADD CONSTRAINT alert_records_alert_event_id_fkey FOREIGN KEY (alert_event_id) REFERENCES public.alert_events(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alert_records
    ADD CONSTRAINT alert_records_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alert_status_history
    ADD CONSTRAINT alert_status_history_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alert_records(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alert_status_history
    ADD CONSTRAINT alert_status_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;
ALTER TABLE ONLY public.alert_suppressions
    ADD CONSTRAINT alert_suppressions_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_service_account_id_fkey FOREIGN KEY (service_account_id) REFERENCES public.service_accounts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.auth_audit_logs
    ADD CONSTRAINT auth_audit_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id);
ALTER TABLE ONLY public.auth_audit_logs
    ADD CONSTRAINT auth_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.beacon_config_history
    ADD CONSTRAINT beacon_config_history_beacon_id_fkey FOREIGN KEY (beacon_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.beacon_configs
    ADD CONSTRAINT beacon_configs_beacon_id_fkey FOREIGN KEY (beacon_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_probe_id_fkey FOREIGN KEY (probe_id) REFERENCES public.probes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.mtr_results
    ADD CONSTRAINT mtr_results_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.probes
    ADD CONSTRAINT probes_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_replaced_by_fkey FOREIGN KEY (replaced_by) REFERENCES public.refresh_tokens(token_id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.token_blacklist
    ADD CONSTRAINT token_blacklist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.webhook_logs
    ADD CONSTRAINT webhook_logs_alert_event_id_fkey FOREIGN KEY (alert_event_id) REFERENCES public.alert_events(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.webhook_logs
    ADD CONSTRAINT webhook_logs_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES public.webhooks(id) ON DELETE CASCADE;
